# Generated by Django 5.1.4 on 2024-12-29 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirportTimeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
        ),
        migrations.AlterModelOptions(
            name="airlinecompany",
            options={"ordering": ["name"], "verbose_name_plural": "airline companies"},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"], "verbose_name_plural": "airplane types"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "countries"},
        ),
        migrations.AlterModelOptions(
            name="facility",
            options={"ordering": ["name"], "verbose_name_plural": "facilities"},
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_time_utc",
            field=models.DateTimeField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_time_utc",
            field=models.DateTimeField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="crew",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crews",
                to="airport.role",
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="time_zone",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="airport.airporttimezone",
            ),
            preserve_default=False,
        ),
    ]
