# Generated by Django 5.1.4 on 2024-12-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_airporttimezone_alter_airlinecompany_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["is_completed", "departure_time"]},
        ),
        migrations.AddField(
            model_name="flight",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
